const SPREADSHEET_ID='COLOCA_AQUI_EL_ID_DE_TU_GOOGLE_SHEET';
const HOJA_ESTUDIANTES='BD_Estudiantes',HOJA_REGISTRO='Registro_Diario',HOJA_JUSTIFICACIONES='Justificaciones';
function doGet(e){try{const action=e.parameter.action||'dashboard';if(action==='dashboard')return jsonResponse(obtenerDashboard(e.parameter.meses));if(action==='estudiantes')return jsonResponse(obtenerEstudiantes());if(action==='buscar_estudiante'){const dni=String(e.parameter.dni||'').trim();if(!/^\d{8}$/.test(dni))return jsonResponse({success:false,message:'El DNI debe tener 8 dígitos'});const estudiante=buscarEstudiante(dni);if(!estudiante)return jsonResponse({success:false,message:'Estudiante no encontrado'});return jsonResponse({success:true,estudiante});}return jsonResponse({success:false,message:'Acción no válida'});}catch(error){return jsonResponse({success:false,message:error.message})}}
function doPost(e){try{const data=JSON.parse(e.postData.contents||'{}');const dni=String(data.dni||'').trim();if(!/^\d{8}$/.test(dni))return jsonResponse({success:false,message:'El DNI debe tener 8 dígitos'});const estudiante=buscarEstudiante(dni);if(!estudiante)return jsonResponse({success:false,message:'Estudiante no encontrado'});const ahora=new Date(),tz=Session.getScriptTimeZone()||'America/Lima',fecha=Utilities.formatDate(ahora,tz,'dd/MM/yyyy'),hora=Utilities.formatDate(ahora,tz,'HH:mm:ss'),estado=calcularEstado(ahora,estudiante.nivel),hoja=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(HOJA_REGISTRO),datos=hoja.getDataRange().getValues();for(let i=1;i<datos.length;i++){if(String(datos[i][0])===fecha&&String(datos[i][2]).trim()===dni)return jsonResponse({success:false,duplicate:true,message:'La asistencia ya fue registrada hoy',estudiante})}hoja.appendRow([fecha,hora,dni,estudiante.nombre,estado]);return jsonResponse({success:true,message:estado==='Asistió'?'Asistencia registrada correctamente':'Asistencia registrada como tardanza',estudiante,asistencia:{fecha,hora,estado}});}catch(error){return jsonResponse({success:false,message:error.message})}}
function buscarEstudiante(dni){const datos=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(HOJA_ESTUDIANTES).getDataRange().getValues();for(let i=1;i<datos.length;i++)if(String(datos[i][0]).trim()===dni)return{dni,nombre:datos[i][1],grado:datos[i][2],nivel:datos[i][3]};return null}
function calcularEstado(fechaHora,nivel){const min=fechaHora.getHours()*60+fechaHora.getMinutes();if(String(nivel).toLowerCase().includes('primaria'))return min<=495?'Asistió':'Tardanza';if(String(nivel).toLowerCase().includes('secundaria'))return min<=855?'Asistió':'Tardanza';return 'Tardanza'}
function obtenerDashboard(meses){meses=Number(meses)||1;const datos=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(HOJA_REGISTRO).getDataRange().getValues(),inicio=new Date();inicio.setMonth(inicio.getMonth()-meses);let total=0,asistencias=0,tardanzas=0,registros=[];for(let i=1;i<datos.length;i++){const f=datos[i][0];if(!f)continue;const fr=f instanceof Date?f:convertirFecha(f);if(fr&&fr>=inicio){registros.push({fecha:datos[i][0],hora:datos[i][1],dni:datos[i][2],nombre:datos[i][3],estado:datos[i][4]});total++;if(datos[i][4]==='Asistió')asistencias++;if(datos[i][4]==='Tardanza')tardanzas++}}return{success:true,filtros:{meses},metricas:{total,asistencias,tardanzas,porcentaje:total?Math.round(asistencias/total*100):0},registros:registros.reverse()}}
function convertirFecha(fecha){const p=String(fecha).split('/');return p.length===3?new Date(Number(p[2]),Number(p[1])-1,Number(p[0])):null}
function obtenerEstudiantes(){const datos=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(HOJA_ESTUDIANTES).getDataRange().getValues();return{success:true,estudiantes:datos.slice(1).map(r=>({dni:String(r[0]),nombre:r[1],grado:r[2],nivel:r[3]}))}}
function jsonResponse(data){return ContentService.createTextOutput(JSON.stringify(data)).setMimeType(ContentService.MimeType.JSON)}